-- Define your custom parameters in Tidal
let cv_val = pF "cv_val"
let port = pI "port"

-- Send a sequence of voltages to ESX-8CV Port 0 (your first bus)
d1 $ s "tidal_cv_ping" # port 0 # cv_val "<0.1 0.5 0.8 0.2>"





d1 $ s "es5gate" # g1 "1 0 1 0" # g2 "0 1 0 1"



--or
-- Define the custom parameters
let cv_val = pF "cv_val"
let port = pI "port"

-- Define a quick alias so you don't have to type out the synth name
let cv = s "tidal_cv_ping"

-- Send a sequence of voltages to ESX-8CV Port 0 (your first modular cable)
d1 $ cv # port 0 # cv_val "<0.1 0.5 0.8 0.2>"

-- Send an LFO (sine wave) generated by Tidal to Port 1!
d2 $ cv # port 1 # cv_val (sine)

-- Pattern port numbers and voltages simultaneously
d3 $ cv # port "2 3 4" # cv_val (choose [0.1, 0.4, 0.9])